networks:
  warehousenetwork:
    name: warehouse-network

services:

  postgres:
    image: postgres:16.3
    ports:
      - 5432:5432
    networks:
      - warehousenetwork
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/pgsql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=postgres1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=WarehouseDb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
      
  pulsar-standalone:
    image: apachepulsar/pulsar:latest
    container_name: pulsar-standalone
    ports:
      - "6650:6650"
      - "8085:8085"
    networks:
      - warehousenetwork
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    command: sh -c "bin/pulsar standalone & \
      sleep 15 && \
      bin/pulsar-admin tenants create wis && \
      bin/pulsar-admin namespaces create wis/inventory  && \
      tail -f /dev/null"

volumes:
  postgres-data:
  pulsardata:
  pulsarconf:

